apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    #pod label
    app: my-app
    env: dev
  namespace: dev
spec:
  containers:
  #create nginx container
  - name: nginx
    image: nginx
    ports:
      - name: http
        containerPort: 80
  

